### ISSUE TITLE
Uncaught TypeError: this.window.webContents.loadUrl is not a function

### ISSUE THREAD

**Issue by alexiej** [tswaters/atom-mocha-runner#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [mocha-runner](https://github.com/tswaters/atom-mocha-runner) package 1.2.0

### Stack Trace

Uncaught TypeError: this.window.webContents.loadUrl is not a function

```
At C:\Users\Arkadiusz\.atom\packages\mocha-runner\lib\window.js:19

TypeError: this.window.webContents.loadUrl is not a function
    at /packages/mocha-runner/lib/window.js:19:27)
    at /packages/mocha-runner/lib/main.js:28:21)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -2:18.9.0 mocha:test (input.hidden-input)
     -2:12.7.0 core:save (input.hidden-input)
  2x -2:10.7.0 mocha:test (input.hidden-input)
  2x -1:49.6.0 atom-mocha:runTestFileFromEditor (div.line.cursor-line.highlight-line)
     -1:37.5.0 atom-mocha:toggle (div.lines)
     -1:29.1.0 atom-mocha:runTestFileFromEditor (div.lines)
  7x -1:25.6.0 mocha:test (div.lines)
     -1:12.8.0 core:cut (input.hidden-input)
     -1:12.4.0 core:save (input.hidden-input)
  2x -1:09.3.0 mocha:test (input.hidden-input)
     -1:04.5.0 atom-mocha:runTestFileFromEditor (div.lines)
     -1:02.4.0 atom-mocha:toggle (div.lines)
     -0:58.7.0 tree-view:reveal-active-file (div.line.cursor-line.highlight-line)
     -0:30.4.0 atom-mocha:runTestFileFromEditor (div.lines)
     -0:28.3.0 mocha:test (div.line)
     -0:07.1.0 mocha-runner:run-specs (input.hidden-input)
```

### Non-Core Packages

```
apex-adapt-dark-ui 0.4.2 
apex-syntax 0.2.0 
apex-ui 1.0.2 
atom-beautify 0.30.5 
atom-bootstrap4 1.4.0 
atom-clock 0.1.15 
atom-file-icons 0.6.0 
atom-formatter-jsbeautify 1.1.2 
atom-karma-test-runner 1.1.1 
atom-live-server 2.2.0 
atom-mocha 0.0.12 
atom-prettify 0.1.3 
atom-python-run 0.9.3 
atom-quokka 1.0.45 
atom-shortcuts 0.0.2 
atom-wallaby 1.0.22 
autocomplete-font-awesome 0.2.1 
autocomplete-python 1.10.3 
bootstrap-vue-snippets 0.4.0 
build 0.69.0 
busy-signal 1.4.3 
city-lights-icons 1.1.1 
compare-files 0.8.1 
copy-as-rtf 0.9.3 
copy-with-style 1.1.0 
current-file-breadcrumb 0.1.2 
Delete-Whitelines 0.6.3 
element-helper 0.5.4 
emmet 2.4.3 
emmet-simplified 2.5.0 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.13 
goto-definition 1.3.4 
hey-pane 1.0.0 
highlight-line 0.12.0 
Hydrogen 2.0.1 
hyperclick 0.1.5 
ide-vue 0.1.7 
imdone-atom 2.2.7 
intentions 1.1.5 
js-hyperclick 1.11.1 
kite 0.60.0 
language-vue 0.23.1 
language-vue-component 0.5.0 
lint-sass-vue 1.0.5 
linter 2.2.0 
linter-htmlhint 1.3.4 
linter-sass-lint 1.8.3 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
lorem 1.3.0 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
mocha 0.0.7 
mocha-runner 1.2.0 
mocha-test-runner 1.0.0 
mocha-ui 0.1.8 
no-title-bar 1.11.3 
node-debugger 1.10.1 
npm-plus 0.4.0 
open-files 0.8.2 
platformio-ide-terminal 2.7.0 
python-terminal 0.2.0 
python-tools 0.6.9 
quick-vue 0.1.0 
scss-element-ui-snippets 0.1.1 
seti-icons 1.5.4 
v-bootstrap4 0.2.1 
vue-autocompile 0.0.6 
vue-autocomplete 0.1.1 
vue-element-ui-snippets 0.7.0 
vue-format 0.4.0 
vue-hyperclick 0.2.0 
vue-stylefmt 0.5.0 
vue-syntax 2.0.0 
vue2-autocomplete 0.1.0-alpha.4 
vuejs-snippets 0.1.0 
vuejs2-snippets 0.14.0 
vuetify-dark-syntax 0.2.0 
Zen 0.18.0 
```

**Comment by tswaters** [comment]
Weird, that's like complete failure to launch isn't it? Did atom change their API at some point?  I'll need to grab the latest version and review the docs...  I don't really use atom or this package any more - switched to vscode.... I'll take a look though.
