### ISSUE TITLE
Uncaught Error: EBADF: bad file descriptor, write

### ISSUE THREAD

**Issue by tswaters** [tswaters/atom-mocha-runner#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [mocha-runner](https://github.com/tswaters/atom-mocha-runner) package, v1.1.3
### Stack Trace

Uncaught Error: EBADF: bad file descriptor, write

```
At C:\Users\Tyler\.atom\packages\mocha-runner\lib\runner.js:40

Error: EBADF: bad file descriptor, write
    at Error (native)
    at Object.fs.writeSync (fs.js:657:20)
    at SyncWriteStream.write (fs.js:1906:6)
    at Console.warn (console.js:44:16)
    at session (C:\Code\sails-example\node_modules\sails\node_modules\express\node_modules\connect\node_modules\express-session\index.js:115:13)
    at Function.session (C:\Code\sails-example\node_modules\sails\node_modules\express\node_modules\connect\lib\middleware\session.js:33:10)
    at C:\Code\sails-example\node_modules\sails\lib\router\index.js:110:49
    at C:\Code\sails-example\node_modules\sails\lib\app\private\after.js:91:14
    at C:\Code\sails-example\node_modules\sails\node_modules\async\lib\async.js:251:17
    at done (C:\Code\sails-example\node_modules\sails\node_modules\async\lib\async.js:132:19)
    at C:\Code\sails-example\node_modules\sails\node_modules\async\lib\async.js:32:16
    at C:\Code\sails-example\node_modules\sails\node_modules\async\lib\async.js:248:21
    at C:\Code\sails-example\node_modules\sails\node_modules\async\lib\async.js:572:34
    at handlerFn (C:\Code\sails-example\node_modules\sails\lib\app\private\after.js:78:13)
    at C:\Code\sails-example\node_modules\sails\node_modules\async\lib\async.js:567:21
    at C:\Code\sails-example\node_modules\sails\node_modules\async\lib\async.js:246:17
```
### Commands

```
     -1:54.4.0 core:select-down (atom-text-editor.editor.is-focused)
     -1:54.1.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:53.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:52.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:51.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:22.8.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -1:20.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -1:20.2.0 find-and-replace:find-next (atom-text-editor.editor.mini.is-focused)
     -1:09.0 core:copy (atom-text-editor.editor.is-focused)
     -1:07.0 core:paste (atom-text-editor.editor.is-focused)
     -1:00.2.0 core:undo (atom-text-editor.editor.is-focused)
     -0:58.1.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  4x -0:57.5.0 find-and-replace:find-next (atom-text-editor.editor.mini.is-focused)
     -0:56.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:56.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:04.6.0 mocha-runner:run-specs (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "mocha-runner": {}
}
```
### Installed Packages

``` coffee
# User
editorconfig, v1.0.0
language-ejs, v0.2.0
linter, v1.0.8
linter-eslint, v1.0.8
linter-jsonlint, v0.1.4
linter-scss-lint, v1.0.5
mocha-runner, v1.1.3

# Dev
No dev packages
```

**Comment by tswaters** [comment]
This is basically dying because of trying to use `console.warn` in the runner process -- need to set up the global console so it sends events back to the main process and logs there.
